version: '3'
services:
  backend:
    build: 
      context: ./country-api-middleware
      dockerfile: ./dockerfile
    container_name: backend
    restart: unless-stopped 
    ports:
      - "4000:4000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./dockerfile
    container_name: frontend
    restart: unless-stopped 
    ports:
      - "3000:3000"   
