version: '3'
services:
  travel-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: travel-backend
    restart: unless-stopped 
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data

  travel-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travel-frontend
    restart: unless-stopped 
    ports:
      - "3001:3000"
