version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - ./database.sqlite:/app/database.sqlite
    restart: unless-stopped
