version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped 
    ports:
      - "49100:49100"
    volumes:
    - ./backend/data:/app/data


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped 
    ports:
      - "3000:3000"   
